import type { NextPage } from 'next'
import Head from 'next/head'
import { PageTemplate, Search, Dish } from "@/components"

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTemplate> 
        <h1>Encontre opções em delivery próximos à você</h1>
        <Search/>
        <h2>Descubra seu novo delivery favorito. Milhares de opções a um clique.</h2>
        <Dish/>
      </PageTemplate>
    </div>
  )
}

export default Home;
